default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: valmy
  password: 12345678
  host: localhost

development:
  <<: *default
  database: find_my_coffee_api_development

test:
  <<: *default
  database: find_my_coffee_api_test

production:
  <<: *default
  database: find_my_coffee_api_production
  username: find_my_coffee
  password: <%= ENV['FIND_MY_COFFEE_DATABASE_PASSWORD'] %>
